prompts = [
  {
    name = "Анализ кода",
    content = "Проанализируй код на {{язык}} и найди потенциальные проблемы:\n\n```{{язык}}\n{{код}}\n```",
    parameters = ["язык", "код"]
  },
  {
    name = "Рефакторинг",
    content = "Предложи способы улучшения этого кода на {{язык}}:\n\n```{{язык}}\n{{код}}\n```\n\nОбрати внимание на:\n- Читаемость\n- Производительность\n- Безопасность",
    parameters = ["язык", "код"]
  },
  {
    name = "Документация",
    content = "Напиши документацию для следующего кода на {{язык}}:\n\n```{{язык}}\n{{код}}\n```",
    parameters = ["язык", "код"]
  },
  {
    name = "Unit тесты",
    content = "Создай unit тесты для этого кода на {{язык}}:\n\n```{{язык}}\n{{код}}\n```",
    parameters = ["язык", "код"]
  },
  {
    name = "Оптимизация",
    content = "Оптимизируй этот код на {{язык}} для лучшей производительности:\n\n```{{язык}}\n{{код}}\n```",
    parameters = ["язык", "код"]
  },
  {
    name = "Объяснение кода",
    content = "Объясни, как работает этот код на {{язык}}:\n\n```{{язык}}\n{{код}}\n```",
    parameters = ["язык", "код"]
  },
  {
    name = "API документация",
    content = "Создай документацию API для этого эндпоинта:\n\nМетод: {{метод}}\nПуть: {{путь}}\n\nПараметры запроса:\n{{параметры}}\n\nОтвет:\n{{ответ}}",
    parameters = ["метод", "путь", "параметры", "ответ"]
  },
  {
    name = "SQL запрос",
    content = "Напиши SQL запрос для {{задача}} с использованием таблиц:\n{{таблицы}}",
    parameters = ["задача", "таблицы"]
  }
]
